## Data Manipulation and Analysis with Pandas

Data manipulation and analaysis are key tasks in any data science or data analysis project.Pandas provides a wide range of functions for data manipulation and analysis, making it easier to cleanm, transform,and extract insights from data. In this lesson, we will cover various data manipulation and anayalsis technique using Pandas.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('ben10_aliens_dataset.csv')
df.head(5)

,name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth
0,Heatblast,Original Series,Classic,Pyronite,Pyros,"Pyrokinesis, Fire Absorption, Flight",160,60,49,50,56,100,0,15,0,21
1,Wildmutt,Original Series,Classic,Vulpimancer,Vulpin,"Enhanced Senses, Agility, Sharp Claws",111,75,70,60,30,6,14,14,0,80
2,Diamondhead,Original Series,Classic,Petrosapien,Petropia,"Crystallokinesis, Crystal Constructs, Durability",157,80,48,100,42,20,8,10,1,28
3,XLR8,Original Series,Classic,Kineceleran,Kinet,"Super Speed, Enhanced Reflexes, Friction Manip...",114,70,100,40,57,10,10,8,0,11
4,Grey Matter,Original Series,Classic,Galvan,Galvan Prime,"Enhanced Intelligence, Small Size, Climbing",113,10,40,10,100,13,13,13,5,80

In [3]:
df.dtypes

name            object
series          object
type            object
species         object
home_world      object
power           object
total_power      int64
combat           int64
speed            int64
durability       int64
intelligence     int64
heat             int64
water            int64
electricity      int64
magic            int64
stealth          int64
dtype: object

Handling Missing Values

In [4]:
df.isnull()

,name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
111,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
112,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
114,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
df.isnull().any()

name            False
series          False
type            False
species         False
home_world      False
power           False
total_power     False
combat          False
speed           False
durability      False
intelligence    False
heat            False
water           False
electricity     False
magic           False
stealth         False
dtype: bool

In [6]:
df.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
110    False
111    False
112    False
113    False
114    False
Length: 115, dtype: bool

In [7]:
df.isnull().sum()

name            0
series          0
type            0
species         0
home_world      0
power           0
total_power     0
combat          0
speed           0
durability      0
intelligence    0
heat            0
water           0
electricity     0
magic           0
stealth         0
dtype: int64

fill those missing values if any have

In [8]:
df.fillna(0)

,name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth
0,Heatblast,Original Series,Classic,Pyronite,Pyros,"Pyrokinesis, Fire Absorption, Flight",160,60,49,50,56,100,0,15,0,21
1,Wildmutt,Original Series,Classic,Vulpimancer,Vulpin,"Enhanced Senses, Agility, Sharp Claws",111,75,70,60,30,6,14,14,0,80
2,Diamondhead,Original Series,Classic,Petrosapien,Petropia,"Crystallokinesis, Crystal Constructs, Durability",157,80,48,100,42,20,8,10,1,28
3,XLR8,Original Series,Classic,Kineceleran,Kinet,"Super Speed, Enhanced Reflexes, Friction Manip...",114,70,100,40,57,10,10,8,0,11
4,Grey Matter,Original Series,Classic,Galvan,Galvan Prime,"Enhanced Intelligence, Small Size, Climbing",113,10,40,10,100,13,13,13,5,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,Omni-Kix Heatblast,Reboot,Omni-Enhanced/Kix,Enhanced Heatblast,Unknown,"Space Armor, Rocket Flight",156,66,55,55,62,100,0,12,5,25
111,Omni-Kix Cannonbolt,Reboot,Omni-Enhanced/Kix,Enhanced Cannonbolt,Unknown,"Tank Treads, Laser Cannons",167,99,93,100,59,14,16,13,5,22
112,Omni-Kix Humungousaur,Reboot,Omni-Enhanced/Kix,Enhanced Humungousaur,Unknown,"Mecha Armor, shockwave Tail",148,100,44,100,39,9,9,7,3,18
113,Omni-Kix Slapback,Reboot,Omni-Enhanced/Kix,Enhanced Slapback,Unknown,"Heavy Armor, Weight Manipulation",134,40,31,94,47,8,13,13,0,26
114,Omni-Naut Jetray,Reboot,Omni-Enhanced/Kix,Enhanced Jetray,Unknown,"Space Flight, Laser Array",159,37,100,52,38,66,88,5,0,14

In [9]:
df_filled=df.fillna(0)

filling missing values with the mean of the coloumn

In [ ]:
df['Ranking']=df['total_power'].fillna(df['total_power'].mean())
df

,name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth,Ranking
0,Heatblast,Original Series,Classic,Pyronite,Pyros,"Pyrokinesis, Fire Absorption, Flight",160,60,49,50,56,100,0,15,0,21,160
1,Wildmutt,Original Series,Classic,Vulpimancer,Vulpin,"Enhanced Senses, Agility, Sharp Claws",111,75,70,60,30,6,14,14,0,80,111
2,Diamondhead,Original Series,Classic,Petrosapien,Petropia,"Crystallokinesis, Crystal Constructs, Durability",157,80,48,100,42,20,8,10,1,28,157
3,XLR8,Original Series,Classic,Kineceleran,Kinet,"Super Speed, Enhanced Reflexes, Friction Manip...",114,70,100,40,57,10,10,8,0,11,114
4,Grey Matter,Original Series,Classic,Galvan,Galvan Prime,"Enhanced Intelligence, Small Size, Climbing",113,10,40,10,100,13,13,13,5,80,113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,Omni-Kix Heatblast,Reboot,Omni-Enhanced/Kix,Enhanced Heatblast,Unknown,"Space Armor, Rocket Flight",156,66,55,55,62,100,0,12,5,25,156
111,Omni-Kix Cannonbolt,Reboot,Omni-Enhanced/Kix,Enhanced Cannonbolt,Unknown,"Tank Treads, Laser Cannons",167,99,93,100,59,14,16,13,5,22,167
112,Omni-Kix Humungousaur,Reboot,Omni-Enhanced/Kix,Enhanced Humungousaur,Unknown,"Mecha Armor, shockwave Tail",148,100,44,100,39,9,9,7,3,18,148
113,Omni-Kix Slapback,Reboot,Omni-Enhanced/Kix,Enhanced Slapback,Unknown,"Heavy Armor, Weight Manipulation",134,40,31,94,47,8,13,13,0,26,134
114,Omni-Naut Jetray,Reboot,Omni-Enhanced/Kix,Enhanced Jetray,Unknown,"Space Flight, Laser Array",159,37,100,52,38,66,88,5,0,14,159

Renaming coloumns

In [13]:
df.dtypes

name            object
series          object
type            object
species         object
home_world      object
power           object
total_power      int64
combat           int64
speed            int64
durability       int64
intelligence     int64
heat             int64
water            int64
electricity      int64
magic            int64
stealth          int64
Ranking          int64
dtype: object

In [24]:
df=df.rename(columns={'name': 'heroes_name' })
df.head()

,heroes_name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth,Ranking
0,Heatblast,Original Series,Classic,Pyronite,Pyros,"Pyrokinesis, Fire Absorption, Flight",160,60,49,50,56,100,0,15,0,21,160
1,Wildmutt,Original Series,Classic,Vulpimancer,Vulpin,"Enhanced Senses, Agility, Sharp Claws",111,75,70,60,30,6,14,14,0,80,111
2,Diamondhead,Original Series,Classic,Petrosapien,Petropia,"Crystallokinesis, Crystal Constructs, Durability",157,80,48,100,42,20,8,10,1,28,157
3,XLR8,Original Series,Classic,Kineceleran,Kinet,"Super Speed, Enhanced Reflexes, Friction Manip...",114,70,100,40,57,10,10,8,0,11,114
4,Grey Matter,Original Series,Classic,Galvan,Galvan Prime,"Enhanced Intelligence, Small Size, Climbing",113,10,40,10,100,13,13,13,5,80,113

Changes data types

In [ ]:
df['new_total_power']=df['total_power'].astype(float) #it will gonna create at the last
df.head()

,heroes_name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth,Ranking,new_total_power
0,Heatblast,Original Series,Classic,Pyronite,Pyros,"Pyrokinesis, Fire Absorption, Flight",160,60,49,50,56,100,0,15,0,21,160,160.0
1,Wildmutt,Original Series,Classic,Vulpimancer,Vulpin,"Enhanced Senses, Agility, Sharp Claws",111,75,70,60,30,6,14,14,0,80,111,111.0
2,Diamondhead,Original Series,Classic,Petrosapien,Petropia,"Crystallokinesis, Crystal Constructs, Durability",157,80,48,100,42,20,8,10,1,28,157,157.0
3,XLR8,Original Series,Classic,Kineceleran,Kinet,"Super Speed, Enhanced Reflexes, Friction Manip...",114,70,100,40,57,10,10,8,0,11,114,114.0
4,Grey Matter,Original Series,Classic,Galvan,Galvan Prime,"Enhanced Intelligence, Small Size, Climbing",113,10,40,10,100,13,13,13,5,80,113,113.0

In [ ]:
df['new_total_power']=df['total_power'].fillna(df['Value'].mean()).astype(float) #it will gonna create at the last
df.head()

In [28]:
df['New_total_power']=df['total_power'].apply(lambda x:x*2)
df.head()

,heroes_name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth,Ranking,new_total_power,New_total_power
0,Heatblast,Original Series,Classic,Pyronite,Pyros,"Pyrokinesis, Fire Absorption, Flight",160,60,49,50,56,100,0,15,0,21,160,160.0,320
1,Wildmutt,Original Series,Classic,Vulpimancer,Vulpin,"Enhanced Senses, Agility, Sharp Claws",111,75,70,60,30,6,14,14,0,80,111,111.0,222
2,Diamondhead,Original Series,Classic,Petrosapien,Petropia,"Crystallokinesis, Crystal Constructs, Durability",157,80,48,100,42,20,8,10,1,28,157,157.0,314
3,XLR8,Original Series,Classic,Kineceleran,Kinet,"Super Speed, Enhanced Reflexes, Friction Manip...",114,70,100,40,57,10,10,8,0,11,114,114.0,228
4,Grey Matter,Original Series,Classic,Galvan,Galvan Prime,"Enhanced Intelligence, Small Size, Climbing",113,10,40,10,100,13,13,13,5,80,113,113.0,226

Grouping Coloumn

mean

In [33]:
grouped_mean=df.groupby('heroes_name')['total_power'].mean()
print(grouped_mean)

heroes_name
Alien X           1000.0
Ampfibian          131.0
Antigravitesla     106.0
Arctiguana         108.0
Armodrillo         116.0
                   ...
Way Big            231.0
Whampire           120.0
Wildmutt           111.0
Wildvine           106.0
XLR8               114.0
Name: total_power, Length: 115, dtype: float64

sum

In [36]:
grouped_sum=df.groupby(['heroes_name','species'])['total_power'].sum()
print(grouped_sum)

heroes_name     species
Alien X         Celestialsapien     1000
Ampfibian       Amperi               131
Antigravitesla  Unknown              106
Arctiguana      Polar Manzardill     108
Armodrillo      Talpaedan            116
                                    ...
Way Big         To'kustar            231
Whampire        Vladat               120
Wildmutt        Vulpimancer          111
Wildvine        Florauna             106
XLR8            Kineceleran          114
Name: total_power, Length: 115, dtype: int64

Aggregate multiple Functions

In [37]:
grouped_age=df.groupby('species')['total_power'].agg(['mean','sum','count'])
grouped_age

                           mean  sum  count
species
Aerophibian               125.0  125      1
Amperi                    131.0  131      1
Appoplexian               113.0  113      1
Arachnichimp              113.0  113      1
Arburian Pelarota         161.0  161      1
...                         ...  ...    ...
Vaxasaurian               158.0  158      1
Vladat                    120.0  120      1
Vreedle                    80.0   80      1
Vulpimancer               111.0  111      1
Way Big / Upchuck Fusion  128.0  128      1

[99 rows x 3 columns]

Merging and joining DataFrames

create sample DataFrames

In [51]:
df1=pd.DataFrame({'key' : ['A','B','C'] , 'Value1':[1,2,3]})
df2=pd.DataFrame({'key' : ['A','B','D'] , 'Value1':[4,5,6]})

In [52]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [53]:
df2

  key  Value1
0   A       4
1   B       5
2   D       6

merging this two dataframe

In [55]:
pd.merge(df1,df2)

Empty DataFrame
Columns: [key, Value1]
Index: []

In [54]:
pd.merge(df1,df2,on='key')

  key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [56]:
pd.merge(df1,df2,on='key',how='inner')

  key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

inner -> only matching rows 

left -> all rows from left df

right -> all rows from right df

outer ->all rows from both

In [57]:
pd.merge(df1,df2,on='key',how='left')

  key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [58]:
pd.merge(df1,df2,on='key',how='right')

  key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6

In [59]:
pd.merge(df1,df2,on='key',how='outer')

  key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0