## Panda-DataFrame And Series

Pandas is a powerful data manipulation libraray in Python, widely used for data analysis and data cleaning.It provides two primary data structures. Series and DataFrame. A series is a one - Dimensional array-like object,while a DataFrame is a two - Dimensional , size-mutable,and potentially heterogenous tabular data structure with labeled axes (rows and columns).

In [4]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\totar\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\totar\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\totar\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\totar\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\totar\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\totar\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd

pandas is 1D array like object that can hold any data type. It is similar to a coloumn in a table.

In [6]:
data=[1,2,3,4,5]
series=pd.Series(data)  ## bada wala S
print("Series \n",series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

create a series from dicitonary

In [7]:
data={'a':1,'b':2,'c':3,'d':4}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
data=[1,2,3,4,5]
index=['a','b','c','d','e']
pd.Series(data,index=index)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
pd.Series(index,index=data)

1    a
2    b
3    c
4    d
5    e
dtype: object

DataFrame

create a dataframe from a dictionary of list

In [14]:
data={
    'Name':['tarun','utkarsh','amit'],
    'Age':[21,20,22],
    'City':['Banglore','New York','Florida']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age      City
0    tarun   21  Banglore
1  utkarsh   20  New York
2     amit   22   Florida
<class 'pandas.core.frame.DataFrame'>

In [15]:
import numpy as np
np.array(df)

array([['tarun', 21, 'Banglore'],
       ['utkarsh', 20, 'New York'],
       ['amit', 22, 'Florida']], dtype=object)

Create a data frame from a list of dictonaries

In [8]:
data=[
    {'Name':'Tarun','Age':21,'Height':6.2},
    {'Name':'Utkarsh','Age':20,'Height':5.9},
    {'Name':'Amit','Age':22,'Height':5.7}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age  Height
0    Tarun   21     6.2
1  Utkarsh   20     5.9
2     Amit   22     5.7
<class 'pandas.core.frame.DataFrame'>

In [9]:
df=pd.read_csv('ben10_aliens_dataset.csv')
df.head(5)

,name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth
0,Heatblast,Original Series,Classic,Pyronite,Pyros,"Pyrokinesis, Fire Absorption, Flight",160,60,49,50,56,100,0,15,0,21
1,Wildmutt,Original Series,Classic,Vulpimancer,Vulpin,"Enhanced Senses, Agility, Sharp Claws",111,75,70,60,30,6,14,14,0,80
2,Diamondhead,Original Series,Classic,Petrosapien,Petropia,"Crystallokinesis, Crystal Constructs, Durability",157,80,48,100,42,20,8,10,1,28
3,XLR8,Original Series,Classic,Kineceleran,Kinet,"Super Speed, Enhanced Reflexes, Friction Manip...",114,70,100,40,57,10,10,8,0,11
4,Grey Matter,Original Series,Classic,Galvan,Galvan Prime,"Enhanced Intelligence, Small Size, Climbing",113,10,40,10,100,13,13,13,5,80

In [10]:
df.tail(5)

,name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth
110,Omni-Kix Heatblast,Reboot,Omni-Enhanced/Kix,Enhanced Heatblast,Unknown,"Space Armor, Rocket Flight",156,66,55,55,62,100,0,12,5,25
111,Omni-Kix Cannonbolt,Reboot,Omni-Enhanced/Kix,Enhanced Cannonbolt,Unknown,"Tank Treads, Laser Cannons",167,99,93,100,59,14,16,13,5,22
112,Omni-Kix Humungousaur,Reboot,Omni-Enhanced/Kix,Enhanced Humungousaur,Unknown,"Mecha Armor, shockwave Tail",148,100,44,100,39,9,9,7,3,18
113,Omni-Kix Slapback,Reboot,Omni-Enhanced/Kix,Enhanced Slapback,Unknown,"Heavy Armor, Weight Manipulation",134,40,31,94,47,8,13,13,0,26
114,Omni-Naut Jetray,Reboot,Omni-Enhanced/Kix,Enhanced Jetray,Unknown,"Space Flight, Laser Array",159,37,100,52,38,66,88,5,0,14

Accessing the data from DataFrame

In [33]:
data=[
    {'Name':'Tarun','Age':21,'Height':6.2},
    {'Name':'Utkarsh','Age':20,'Height':5.9},
    {'Name':'Amit','Age':22,'Height':5.7}
]
df=pd.DataFrame(data)
print(df)

      Name  Age  Height
0    Tarun   21     6.2
1  Utkarsh   20     5.9
2     Amit   22     5.7

In [12]:
df['Name']

0      Tarun
1    Utkarsh
2       Amit
Name: Name, dtype: object

In [13]:
df.loc[0]

Name      Tarun
Age          21
Height      6.2
Name: 0, dtype: object

In [14]:
df.loc[1][0]

C:\Users\totar\AppData\Local\Temp\ipykernel_15776\2044023174.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[1][0]

'Utkarsh'

Accessing a specified element

In [17]:
df.at[0,'Age']

np.int64(21)

Pandas uses NumPy internally to store data. So all numbers in a DataFrame are NumPy types, not plain Python types.

Python integer → 21
NumPy integer → np.int64(21)

In [18]:
print(df.at[0,'Age'])

21

ACcessing a specified element using (iat)

In [20]:
print(df.iat[2,2])

5.7

In [21]:
df

      Name  Age  Height
0    Tarun   21     6.2
1  Utkarsh   20     5.9
2     Amit   22     5.7

Data Manipultaion with DataFrame

In [22]:
df['Occupation']=['Student','Friend 1','Friend 2']
df

      Name  Age  Height Occupation
0    Tarun   21     6.2    Student
1  Utkarsh   20     5.9   Friend 1
2     Amit   22     5.7   Friend 2

Remove a coloumn

In [ ]:
df.drop('Occupation') ##{KeyError: "['Occupation'] not found in axis"} -> you
##will find this error over here,its bcoz   its going by default in row(axis=0) not in coloumn so it will find 0 ,1 ,2 but when we assign axis=1(for coloumn) then it will find name,age,height,occupation

KeyError: "['Occupation'] not found in axis"

In [24]:
df.drop('Occupation',axis=1)

      Name  Age  Height
0    Tarun   21     6.2
1  Utkarsh   20     5.9
2     Amit   22     5.7

inplace (what it do, is just that it remove that coloumn permanently)

In [ ]:
df ## (here you will find that table is not delete)

      Name  Age  Height Occupation
0    Tarun   21     6.2    Student
1  Utkarsh   20     5.9   Friend 1
2     Amit   22     5.7   Friend 2

In [26]:
df.drop('Occupation',axis=1,inplace=True) ##not it will remove permanently

In [27]:
df

      Name  Age  Height
0    Tarun   21     6.2
1  Utkarsh   20     5.9
2     Amit   22     5.7

Add age to coloumn

In [32]:
df['Age']=df['Age']+1
df

      Name  Age  Height
0    Tarun   23     6.2
1  Utkarsh   22     5.9
2     Amit   24     5.7
3     Amit   23     5.7
4  unk now   23     5.7

Add another row

In [34]:
new_row = {'Name': 'unk now', 'Age': 22, 'Height': 5.7}

df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

print(df)

      Name  Age  Height
0    Tarun   21     6.2
1  Utkarsh   20     5.9
2     Amit   22     5.7
3  unk now   22     5.7

In [35]:
df.drop(3) ## but for permantely delete you have to use inplace

      Name  Age  Height
0    Tarun   21     6.2
1  Utkarsh   20     5.9
2     Amit   22     5.7

In [36]:
df.describe()

             Age    Height
count   4.000000  4.000000
mean   21.250000  5.875000
std     0.957427  0.236291
min    20.000000  5.700000
25%    20.750000  5.700000
50%    21.500000  5.800000
75%    22.000000  5.975000
max    22.000000  6.200000